export { default as Layout } from './Layout.vue'
export { default as Header } from './Header.vue'
export { default as Sider } from './Sider.vue'
export { default as Content } from './Content.vue'
export { default as Footer } from './Footer.vue'